// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Nf6_qtTDGwbJUq5Y1GJLnnoQ9g3HM28',
    appId: '1:311296270676:web:b45be6a2372313e110a8c1',
    messagingSenderId: '311296270676',
    projectId: 'project-6b27d',
    authDomain: 'project-6b27d.firebaseapp.com',
    storageBucket: 'project-6b27d.appspot.com',
    measurementId: 'G-QVVWK67BE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAUDBUvyQ6skBGahHqk_dTuHbKlk6R86I',
    appId: '1:311296270676:android:e3be2d1f9f4cf79310a8c1',
    messagingSenderId: '311296270676',
    projectId: 'project-6b27d',
    storageBucket: 'project-6b27d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3dq5KVFTGDxzgaiUNH5A3ROl022yRNeI',
    appId: '1:311296270676:ios:b30aa10ca57aab8e10a8c1',
    messagingSenderId: '311296270676',
    projectId: 'project-6b27d',
    storageBucket: 'project-6b27d.appspot.com',
    iosBundleId: 'com.example.projectJdvillamin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3dq5KVFTGDxzgaiUNH5A3ROl022yRNeI',
    appId: '1:311296270676:ios:b30aa10ca57aab8e10a8c1',
    messagingSenderId: '311296270676',
    projectId: 'project-6b27d',
    storageBucket: 'project-6b27d.appspot.com',
    iosBundleId: 'com.example.projectJdvillamin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Nf6_qtTDGwbJUq5Y1GJLnnoQ9g3HM28',
    appId: '1:311296270676:web:677b340ac691d8f210a8c1',
    messagingSenderId: '311296270676',
    projectId: 'project-6b27d',
    authDomain: 'project-6b27d.firebaseapp.com',
    storageBucket: 'project-6b27d.appspot.com',
    measurementId: 'G-H1L3T4M1TV',
  );

}